/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#0053db",
        "inverse-primary": "#b4c5ff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "primary-fixed": "#dbe1ff",
        "tertiary": "#4d556b",
        "on-primary-container": "#eeefff",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed-dim": "#b7c8e1",
        "on-surface": "#191c1e",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed-variant": "#003ea8",
        "outline-variant": "#c3c6d7",
        "on-error-container": "#93000a",
        "primary": "#004ac6",
        "on-primary-fixed": "#00174b",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed-variant": "#3f465c",
        "surface-dim": "#d8dadc",
        "secondary-fixed": "#d3e4fe",
        "error-container": "#ffdad6",
        "surface": "#f7f9fb",
        "outline": "#737686",
        "on-error": "#ffffff",
        "primary-container": "#2563eb",
        "inverse-on-surface": "#eff1f3",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#131b2e",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "secondary": "#505f76",
        "tertiary-container": "#656d84",
        "on-tertiary-container": "#eef0ff",
        "inverse-surface": "#2d3133",
        "on-surface-variant": "#434655",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed-dim": "#bec6e0",
        "on-secondary-container": "#54647a",
        "background": "#f7f9fb",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed": "#dae2fd",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#0b1c30",
        "secondary-container": "#d0e1fb"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "4px",
        "lg": "24px",
        "sm": "12px",
        "xs": "8px",
        "2xl": "48px",
        "gutter": "24px",
        "md": "16px",
        "container-max": "1440px",
        "xl": "32px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-data": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
